### ISSUE TITLE
Conversion from unit to double

### ISSUE THREAD

**Issue by 0xffox** [df7cb/postgresql-unit#26]
Is there a way to convert form units to double precision.
I want to convert centimeters into foots(feet?) without the need to convert it to/from text to avoid rounding error. Basically I want something like `value_at('0.3333 cm'::unit, 'ft')` to return just a double precision number.
Or maybe there is another way to accomplish that?

**Comment by df7cb** [comment]
Hi,
use the `@@` operator:

```
select '0.333m'::unit @@ 'ft';
     ?column?     
──────────────────
 1.09251968503937
```

**Comment by 0xffox** [comment]
Thank you very much!
