### ISSUE TITLE
Carbon Footprint

### ISSUE THREAD

**Issue by dwolfson** [df7cb/postgresql-unit#35]
I was wondering if there is an easy way to add CO2e to units? Carbon Dioxide equivalence is a way to normalize different greenhouse gases..

The standard unit for measuring carbon footprints is the Carbon dioxide equivalent (CO2e), which is expressed as parts per million by volume, ppmv. The idea is to express the impact of each different greenhouse gas in terms of the amount of CO2 that would create the same amount of warming. That way, a carbon footprint consisting of lots of different greenhouse gases can be expressed as a single number.

Not quite sure how to add this concept?

**Comment by df7cb** [comment]
Hi Dan,

I'm not familiar with that unit, but if it's a "normal" physical unit that can be expressed in SI base units, you can do this:
```
postgres =# insert into unit_units values ('co2equiv', 'ppm/m³');
INSERT 0 1
postgres=# select '500 co2equiv'::unit;
    unit     
─────────────
 0.0005 m^-3

postgres =# insert into unit_units values ('methane_equiv', '84 co2equiv');
INSERT 0 1
postgres=# select 'methane_equiv'::unit;
     unit     
──────────────
 8.4e-05 m^-3
```

The default list of units is imported from GNU units, so ideally these units would be added there first.

If it's more complicated than that, GNU units has the notion of functions and lookup tables, but postgresql-unit doesn't implement these yet. (Though I'm open to idea how to implement them.)

**Comment by df7cb** [comment]
If you are still interested, please get in touch with GNU units to get the definitions added there first.

**Comment by dwolfson** [comment]
Thanks for reminding me! Let me take a look again and give it some thought…I have some upcoming discussions related to this with other users so will see what I can learn.

Dan
