### ISSUE TITLE
Mathematical Operators vs unit_ functions

### ISSUE THREAD

**Issue by clausMeko** [df7cb/postgresql-unit#36]
Hi,

I was wondering why I am getting issues like that at some places:

`operator does not exist: double precision * public.unit` and need to use functions like:
* `unit_dbl_mul`
* `unit_sub`
* ...

While on other places I can get away with plain operators like:
* `3 * '4 mm:unit'`
* `'3 cm'::unit - '4 mm:unit' `

Can you explain that?

**Comment by df7cb** [comment]
Operators live in schemas as well. If public is not in search_path, you have to use `operator(public.*)`:

```
# select 5 * '3A'::public.unit;
FEHLER:  42883: Operator existiert nicht: integer * public.unit

# select 5 operator(public.*) '3A'::public.unit;
 ?column? 
──────────
 15 A
```
