### ISSUE TITLE
New Unit prefixes

### ISSUE THREAD

**Issue by 0xflotus** [df7cb/postgresql-unit#37]
The [Wikipedia site of the metric prefixes](https://en.wikipedia.org/wiki/Metric_prefix) shows new unit prefixes:

| Name   | Symbol | Base 10 |
|--------|--------|---------|
| quetta | Q      | 1e30    |
| ronna  | R      | 1e27    |
| ronto  | r      | 1e-27   |
| quecto | q      | 1e-30   |

It was adopted by [BIPM](https://www.bipm.org/en/measurement-units/si-prefixes) in 2022

What do you think? Should this prefixes be implemented?

**Comment by df7cb** [comment]
I had seen the announcement, but haven't had the time yet to add them. Will do so shortly, thanks for the reminder!

**Comment by 0xflotus** [comment]
Any news on this?
Is it an easy task to add the new prefixes or is it complicated? 
I saw a `unit_prefixes.data` file. Is this file related to the addition?

**Comment by df7cb** [comment]
unit_prefixes.data is one of the bits that needs changing, but it also needs C code adjustments. Stay tuned.

**Comment by df7cb** [comment]
Done in 5eacc8e2608b6c6d01.
